### ISSUE TITLE
How did you get the title bar in NVIM?

### ISSUE THREAD

**Issue by FormalSnake** [stevedylandev/dotfiles#1]
I want this:
![image](https://github.com/stevedylandev/dotfiles/assets/90651091/2250ab14-0d3c-4d6a-a5f7-77bd62b35ba6)
And I modified my own config to use some of yours for aesthetical reasons, but I do not have the title bar.
![Screenshot 2024-01-04 at 16 35 24](https://github.com/stevedylandev/dotfiles/assets/90651091/653ccdbe-724c-4aa5-befc-fa50cb723978)
Also, what wallpaper do you use? It fits really nicely :D

**Comment by stevedylandev** [comment]
That is actually tmux! If you copy the `.tmux.conf` file to your home directory (`~/`) then run tmux it should appear. Keep in mind I did do some custom keymappings that make it a little different than your normal tmux config, e.g. prefix is `Ctrl + q` instead of `Ctrl + b`. 

Just updated the repo for my wallpapers so you can find it here! :) https://github.com/stevedylandev/wallpapers/blob/main/assets/pexels-lewis-ashton-10691833.jpg

**Comment by FormalSnake** [comment]
Oh nice!
![Screenshot 2024-01-04 at 17 40 42](https://github.com/stevedylandev/dotfiles/assets/90651091/570b0ae5-0b8b-47c7-895e-62d95f7eba9c)
Thank you very much! These dotfiles are fire! I had no issues except when the fuzzy finder was outdated (a guide could be nice)
I am going to use these as inspiration for my dots if you don't mind.

**Comment by stevedylandev** [comment]
No problem! So glad you liked them :) Please do feel free to use them!

**Comment by stevedylandev** [comment]
I'll need to look into that fuzzy finder issue
